# 47. 에러처리

## 47.4 throw 문

```js
try {
  new Error("장비를 정지합니다");
} catch (error) {
  console.log(ereor);
}
```

에러 객체를 생성한다고 해서 에러가 발생하지 않는다.

에러를 발생시키려면 `try` 블록에서 `throw` 문으로 에러객체를 던져야한다.

```js
try {
  throw new Error("장비를 정지합니다");
} catch (error) {
  console.log(ereor);
}
```

에러를 던지면 `catch` 문에 의해 에러 변수가 생성되고, 에러객체가 할당된다.

```js
const repeat = (n, f) => {
  if (typeof f !== function) throw new TypeError('함수가 이상한데요?');

  for (var i = 0; i < n; i++) {
    f(i);
  }
};

try {
  repeat(2,1);
} catch (err) {
  console.log(err);
}
```
